apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: gustavoh430/login_app
          env:
            - name: SPRING.DATASOURCE.URL
              value: "jdbc:mysql://mysql-service.default:3306/UserDatabase?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC"

---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



